### ISSUE TITLE
How to make the sidebar more wider?

### ISSUE THREAD

**Issue by joshuarobs** [ankitskvmdam/clean-jsdoc-theme#50]
Currently its set at 250px by default, is there an option to set this to make it more wider? I tried looking into the css and changing the width myself, but it doesn't make the main content move, i.e. the sidebar gets wider but covers the docs

**Comment by ankitskvmdam** [comment]
There are two ways of doing this.
1. In your `jsdoc-config.json` under `opts` first you have to include `theme_opts` key. Then under `theme_opts` add `create_style` key with value, `"nav {width: 300px} #main {margin-left: 300px} @media (max-width: 672px) { nav {left: -300px} #main{margin-left: 0}}"`. Note: nav width must be equal to #main margin-left.
Your `jsdoc-config` file will look something like this:
```json5
// jsdoc-config.json
{ 
    ...
    ...
    "opts": {
        ...
        ...
        "theme_opts": {
            "create_style": "nav {width: 300px} #main {margin-left: 300px} @media (max-width: 672px) { nav {left: -300px} #main{margin-left: 0}}"
        }
    },
}
```

2. Alternatively you can add your custom css file path:
```css
/* custom.css */
nav {
    width: 300px
} 

#main {
    margin-left: 300px
}

@media (max-width: 672px) {
    nav {
        left: -300px
    } 

    #main {
        margin-left: 0
    }
}
```
```json5
// jsdoc-config.json
{ 
    ...
    ...
    "opts": {
        ...
        ...
        "theme_opts": {
           "add_style_path": ["custom.css"] //Note path must be relative to your output file. (relative to generated html files.)
           // And you have to manually copy all the css to the output directory.
        }
    },
}
```
